apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mimir-single.fullname" . }}
  labels:
    {{- include "mimir-single.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mimir-single.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if or .Values.podAnnotations (and .Values.serviceMesh.enabled .Values.serviceMesh.annotations) }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if and .Values.serviceMesh.enabled .Values.serviceMesh.annotations }}
        {{- toYaml .Values.serviceMesh.annotations | nindent 8 }}
        {{- end }}
      {{- end }}
      labels:
        {{- include "mimir-single.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mimir-single.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "mimir-single.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - mimir
            - -config.file=/etc/mimir.yaml
            - -auth.multitenancy-enabled=false
            - -auth.no-auth-tenant=anonymous
          ports:
            - name: web
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: http
              containerPort: 9095
            - name: grpc
              containerPort: 9195
            - name: ingester
              containerPort: 9094
            - name: memberlist
              containerPort: 7946
          startupProbe:
            {{- toYaml .Values.probes.startup | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.probes.liveness | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.probes.readiness | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: mimir-config-volume
              mountPath: /etc/mimir.yaml
              subPath: mimir.yaml
              readOnly: true
            - name: tmp
              mountPath: /tmp
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: mimir-config-volume
          configMap:
            name: {{ include "mimir-single.fullname" . }}-config
            defaultMode: 420
        - name: tmp
          emptyDir:
            sizeLimit: 1Gi
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
